// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTask struct {
	Title       string  `json:"title"`
	Description *string `json:"description"`
	UserID      int     `json:"userId"`
}

type Task struct {
	ID          int     `json:"id"`
	Title       string  `json:"title"`
	Description *string `json:"description"`
	Done        bool    `json:"done"`
	User        *User   `json:"user"`
}

type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}
