package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"fmt"
	"math/rand"

	"github.com/mercadolibre/graphql-example/graph/model"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.NewTask) (*model.Task, error) {
	rand := rand.Intn(1000)

	if input.Title == "" {
		return nil, fmt.Errorf("title cannot be nil")
	}

	if input.UserID == 0 {
		return nil, fmt.Errorf("userID cannot be nil")
	}

	user := &model.User{
		ID:   input.UserID,
		Name: fmt.Sprintf("user_%d", input.UserID),
	}

	users = append(users, user)

	task := &model.Task{
		ID:          rand,
		Title:       input.Title,
		Description: input.Description,
		User:        user,
	}

	tasks = append(tasks, task)

	return task, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
	return tasks, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id int) (*model.Task, error) {
	panic(fmt.Errorf("not implemented: Task - task"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
var tasks []*model.Task
var users []*model.User
